export {
  IDENTITY_MATRIX,
  SingularMatrixError,
  isValidMatrix,
  matrixApply,
  matrixInvert,
  matrixMultiply,
  matrixRotate,
  matrixScale,
  matrixTranslate,
  transformRectBounds,
  type Mat2D,
} from "./geometry.js";
export {
  INTERACTION_TREE_FORMAT_VERSION,
  InteractionTreeValidationError,
  childrenOf,
  createInteractionTree,
  nodeById,
  pathToRoot,
  type InteractionClip,
  type InteractionNode,
  type InteractionNodeInit,
  type InteractionTree,
} from "./interaction-tree.js";
export {
  codeSegmenter,
  completeJsonPrefix,
  jsonSegmenter,
  markdownSegmenter,
  rowsSegmenter,
  textSegmenter,
} from "./segmenters.js";
export {
  ARTIFACT_BUNDLE_FORMAT_VERSION,
  HIBERNATION_FORMAT_VERSION,
  SerializationError,
  assertDurableState,
  canonicalStringify,
  deserializeArtifactBundle,
  deserializeHibernationRecord,
  serializeArtifactBundle,
  serializeHibernationRecord,
  type ArtifactBundle,
  type ArtifactSource,
  type ArtifactSourceKind,
  type DurableState,
  type HibernationRecord,
} from "./serialization.js";
